/*
 * Created on 9 avr. 2015 ( Time 11:50:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.silanis.lottery.bean.jpa.WinnerEntity;
import com.silanis.lottery.persistence.commons.fake.GenericFakeService;
import com.silanis.lottery.persistence.services.WinnerPersistence;

/**
 * Fake persistence service implementation ( entity "Winner" )
 *
 * @author Telosys Tools Generator
 */
public class WinnerPersistenceFAKE extends GenericFakeService<WinnerEntity> implements WinnerPersistence {

	public WinnerPersistenceFAKE () {
		super(WinnerEntity.class);
	}
	
	protected WinnerEntity buildEntity(int index) {
		WinnerEntity entity = new WinnerEntity();
		// Init fields with mock values
		entity.setPosition( nextInteger() ) ;
		entity.setAmount( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(WinnerEntity entity) {
		log("delete ( WinnerEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer idTicket, Integer idDraw ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(WinnerEntity entity) {
		log("insert ( WinnerEntity : " + entity + ")" ) ;
	}

	public WinnerEntity load( Integer idTicket, Integer idDraw ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<WinnerEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<WinnerEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<WinnerEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public WinnerEntity save(WinnerEntity entity) {
		log("insert ( WinnerEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<WinnerEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
