/*
 * Created on 9 avr. 2015 ( Time 11:50:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.business.service;

import java.util.List;

import com.silanis.lottery.bean.Draw;

/**
 * Business Service Interface for entity Draw.
 */
public interface DrawService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idDraw
	 * @return entity
	 */
	Draw findById( Integer idDraw  ) ;


	/**
	 * Loads an entity from the database using its Primary Key
	 * Then launch the draw to get and save the winners to DB
	 * @param idDraw
	 * @return entity
	 */
	void launchById(Integer idDraw);
	
	/**
	 * Loads an entity from the database using its Primary Key, the object will contain the list of participants and list of winners filled
	 * @param idDraw
	 * @return entity
	 */
	Draw findByIdIncludingParticipantAndWinners( Integer idDraw  ) ;
	
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Draw> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Draw save(Draw entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Draw update(Draw entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Draw create(Draw entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idDraw
	 */
	void delete( Integer idDraw );


}
