/*
 * Created on 9 avr. 2015 ( Time 11:50:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.business.service;

import java.util.List;

import com.silanis.lottery.bean.Winner;

/**
 * Business Service Interface for entity Winner.
 */
public interface WinnerService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idTicket
	 * @param idDraw
	 * @return entity
	 */
	Winner findById( Integer idTicket, Integer idDraw  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Winner> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Winner save(Winner entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Winner update(Winner entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Winner create(Winner entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idTicket
	 * @param idDraw
	 */
	void delete( Integer idTicket, Integer idDraw );


}
