/*
 * Created on 9 avr. 2015 ( Time 11:50:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.web.listitem;

import com.silanis.lottery.bean.Draw;
import com.silanis.lottery.web.common.ListItem;

public class DrawListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public DrawListItem(Draw draw) {
		super();

		this.value = ""
			 + draw.getIdDraw()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = draw.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
