/*
 * Created on 9 avr. 2015 ( Time 11:50:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.silanis.lottery.persistence.services.jpa;


import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.silanis.lottery.bean.jpa.DrawEntity;
import com.silanis.lottery.bean.jpa.TicketEntity;
import com.silanis.lottery.bean.jpa.WinnerEntity;
import com.silanis.lottery.persistence.commons.jpa.GenericJpaService;
import com.silanis.lottery.persistence.commons.jpa.JpaOperation;
import com.silanis.lottery.persistence.services.DrawPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Draw" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class DrawPersistenceJPA extends GenericJpaService<DrawEntity, Integer> implements DrawPersistence {

	/**
	 * Constructor
	 */
	public DrawPersistenceJPA() {
		super(DrawEntity.class);
	}

	@Override
	public DrawEntity load( Integer idDraw ) {
		return super.load( idDraw );
	}
	
	@Override
	public DrawEntity loadIncludingParticipantAndWinners( final Integer idDraw ) {
		
		
		JpaOperation operation = new JpaOperation() {
			@Override
			public DrawEntity exectue(EntityManager em) throws PersistenceException {
				DrawEntity drawEntityReturned = em.find(DrawEntity.class, idDraw);
				if(drawEntityReturned!=null)
				{
					drawEntityReturned.getListOfTicket().size();
					drawEntityReturned.getListOfWinner().size();
				}
				return drawEntityReturned;
			}
		} ;
		// JPA operation execution 
		DrawEntity drawEntity = (DrawEntity) execute(operation) ;
		return drawEntity;
		
		
		
	}

	@Override
	public boolean delete( Integer idDraw ) {
		return super.delete( idDraw );
	}

	@Override
	public boolean delete(DrawEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdDraw() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("DrawEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
