/*
 * Created on 9 avr. 2015 ( Time 11:50:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.silanis.lottery.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.silanis.lottery.bean.jpa.WinnerEntity;
import com.silanis.lottery.bean.jpa.WinnerEntityKey;
import com.silanis.lottery.persistence.commons.jpa.GenericJpaService;
import com.silanis.lottery.persistence.commons.jpa.JpaOperation;
import com.silanis.lottery.persistence.services.WinnerPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Winner" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class WinnerPersistenceJPA extends GenericJpaService<WinnerEntity, WinnerEntityKey> implements WinnerPersistence {

	/**
	 * Constructor
	 */
	public WinnerPersistenceJPA() {
		super(WinnerEntity.class);
	}

	@Override
	public WinnerEntity load( Integer idTicket, Integer idDraw ) {
		// Build the composite key
		WinnerEntityKey key = new WinnerEntityKey( idTicket, idDraw );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer idTicket, Integer idDraw ) {
		// Build the composite key
		WinnerEntityKey key = new WinnerEntityKey( idTicket, idDraw );
		return super.delete( key );
	}

	@Override
	public boolean delete(WinnerEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			WinnerEntityKey key = new WinnerEntityKey( entity.getIdTicket(), entity.getIdDraw() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("WinnerEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
