/*
 * Created on 9 avr. 2015 ( Time 11:50:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Draw implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer idDraw;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Date creationDate;

    @NotNull
    private Date drawDate;

    private Boolean isOpen;
    
    private List<Ticket> listTickets;
    private List<Winner> listWinners;

   

	//----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdDraw( Integer idDraw ) {
        this.idDraw = idDraw ;
    }

    public Integer getIdDraw() {
        return this.idDraw;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCreationDate( Date creationDate ) {
        this.creationDate = creationDate;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setDrawDate( Date drawDate ) {
        this.drawDate = drawDate;
    }
    public Date getDrawDate() {
        return this.drawDate;
    }

    public void setIsOpen( Boolean isOpen ) {
        this.isOpen = isOpen;
    }
    public Boolean getIsOpen() {
        return this.isOpen;
    }

    
    public List<Ticket> getListTickets() {
		if(listTickets==null)
		{
			listTickets = new ArrayList<Ticket>();
		}
		return listTickets;
		
	}

	public void setListTickets(List<Ticket> listTickets) {
		this.listTickets = listTickets;
	}

	public List<Winner> getListWinners() {
		if(listWinners==null)
		{
			listWinners = new ArrayList<Winner>();
		}
		
			return listWinners;
		
	}

	public void setListWinners(List<Winner> listWinners) {
		this.listWinners = listWinners;
	}

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idDraw);
        sb.append("|");
        sb.append(creationDate);
        sb.append("|");
        sb.append(drawDate);
        sb.append("|");
        sb.append(isOpen);
        return sb.toString(); 
    } 


}
