/*
 * Created on 9 avr. 2015 ( Time 11:50:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Winner implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idTicket;
    @NotNull
    private Integer idDraw;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer position;

    @NotNull
    private Integer amount;
    
    private String participantName;




	//----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTicket( Integer idTicket ) {
        this.idTicket = idTicket ;
    }

    public Integer getIdTicket() {
        return this.idTicket;
    }

    public void setIdDraw( Integer idDraw ) {
        this.idDraw = idDraw ;
    }

    public Integer getIdDraw() {
        return this.idDraw;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPosition( Integer position ) {
        this.position = position;
    }
    public Integer getPosition() {
        return this.position;
    }

    public void setAmount( Integer amount ) {
        this.amount = amount;
    }
    public Integer getAmount() {
        return this.amount;
    }


    public String getParticipantName() {
		return participantName;
	}

	public void setParticipantName(String participantName) {
		this.participantName = participantName;
	}

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTicket);
        sb.append("|");
        sb.append(idDraw);
        sb.append("|");
        sb.append(position);
        sb.append("|");
        sb.append(amount);
        return sb.toString(); 
    } 


}
