/*
 * Created on 9 avr. 2015 ( Time 11:50:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.web.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

/**
 * Spring MVC controller for 'Winner' management.
 */
@Controller
public class SecurityController{

	//Spring Security see this :
		@RequestMapping(value = "/login", method = RequestMethod.GET)
		public ModelAndView login(){
	 
			ModelAndView model = new ModelAndView();
		
			model.setViewName("login");
	 
			return model;
	 
		}
		@RequestMapping(value = "/login/error", method = RequestMethod.GET)
		public ModelAndView loginError(){
	 
			ModelAndView model = new ModelAndView();
		
			model.addObject("error", "Invalid username and password!");
			
			model.setViewName("login");
	 
			return model;
	 
		}

}
