/*
 * Created on 9 avr. 2015 ( Time 11:50:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.silanis.lottery.bean.Draw;
import com.silanis.lottery.bean.jpa.DrawEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class DrawServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public DrawServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'DrawEntity' to 'Draw'
	 * @param drawEntity
	 */
	public Draw mapDrawEntityToDraw(DrawEntity drawEntity) {
		if(drawEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Draw draw = map(drawEntity, Draw.class);

		return draw;
	}
	
	/**
	 * Mapping from 'Draw' to 'DrawEntity'
	 * @param draw
	 * @param drawEntity
	 */
	public void mapDrawToDrawEntity(Draw draw, DrawEntity drawEntity) {
		if(draw == null) {
			return;
		}

		//--- Generic mapping 
		map(draw, drawEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}