/*
 * Created on 9 avr. 2015 ( Time 11:50:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.silanis.lottery.bean.Ticket;
import com.silanis.lottery.bean.jpa.TicketEntity;
import com.silanis.lottery.bean.jpa.DrawEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TicketServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TicketServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TicketEntity' to 'Ticket'
	 * @param ticketEntity
	 */
	public Ticket mapTicketEntityToTicket(TicketEntity ticketEntity) {
		if(ticketEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Ticket ticket = map(ticketEntity, Ticket.class);

		//--- Link mapping ( link to Draw )
		if(ticketEntity.getDraw() != null) {
			ticket.setIdDraw(ticketEntity.getDraw().getIdDraw());
		}
		return ticket;
	}
	
	/**
	 * Mapping from 'Ticket' to 'TicketEntity'
	 * @param ticket
	 * @param ticketEntity
	 */
	public void mapTicketToTicketEntity(Ticket ticket, TicketEntity ticketEntity) {
		if(ticket == null) {
			return;
		}

		//--- Generic mapping 
		map(ticket, ticketEntity);

		//--- Link mapping ( link : ticket )
		if( hasLinkToDraw(ticket) ) {
			DrawEntity draw1 = new DrawEntity();
			draw1.setIdDraw( ticket.getIdDraw() );
			ticketEntity.setDraw( draw1 );
		} else {
			ticketEntity.setDraw( null );
		}

	}
	
	/**
	 * Verify that Draw id is valid.
	 * @param Draw Draw
	 * @return boolean
	 */
	private boolean hasLinkToDraw(Ticket ticket) {
		if(ticket.getIdDraw() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}