/*
 * Created on 9 avr. 2015 ( Time 11:50:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.silanis.lottery.bean.Winner;
import com.silanis.lottery.bean.jpa.WinnerEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class WinnerServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public WinnerServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'WinnerEntity' to 'Winner'
	 * @param winnerEntity
	 */
	public Winner mapWinnerEntityToWinner(WinnerEntity winnerEntity) {
		if(winnerEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Winner winner = map(winnerEntity, Winner.class);

		return winner;
	}
	
	/**
	 * Mapping from 'Winner' to 'WinnerEntity'
	 * @param winner
	 * @param winnerEntity
	 */
	public void mapWinnerToWinnerEntity(Winner winner, WinnerEntity winnerEntity) {
		if(winner == null) {
			return;
		}

		//--- Generic mapping 
		map(winner, winnerEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}