/*
 * Created on 9 avr. 2015 ( Time 11:50:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.persistence.services;

import java.util.List;
import java.util.Map;

import com.silanis.lottery.bean.jpa.DrawEntity;

/**
 * Basic persistence operations for entity "Draw"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface DrawPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param draw
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(DrawEntity draw) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idDraw
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idDraw) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param draw
	 */
	public void insert(DrawEntity draw) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idDraw
	 * @return the entity loaded (or null if not found)
	 */
	public DrawEntity load(Integer idDraw) ;
	
	/**
	 * Loads the entity for the given Primary Key  , the object will contain the list of participants and list of winners filled<br>
	 * @param idDraw
	 * @return the entity loaded (or null if not found)
	 */
	public DrawEntity loadIncludingParticipantAndWinners(Integer idDraw) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<DrawEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<DrawEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<DrawEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param draw
	 * @return
	 */
	public DrawEntity save(DrawEntity draw) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<DrawEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
