/*
 * Created on 9 avr. 2015 ( Time 11:50:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.persistence.services;

import java.util.List;
import java.util.Map;

import com.silanis.lottery.bean.jpa.TicketEntity;

/**
 * Basic persistence operations for entity "Ticket"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface TicketPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param ticket
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(TicketEntity ticket) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idTicket
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idTicket) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param ticket
	 */
	public void insert(TicketEntity ticket) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idTicket
	 * @return the entity loaded (or null if not found)
	 */
	public TicketEntity load(Integer idTicket) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<TicketEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<TicketEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<TicketEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param ticket
	 * @return
	 */
	public TicketEntity save(TicketEntity ticket) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<TicketEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
