/*
 * Created on 9 avr. 2015 ( Time 11:50:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.silanis.lottery.persistence.services;

import java.util.List;
import java.util.Map;

import com.silanis.lottery.bean.jpa.WinnerEntity;

/**
 * Basic persistence operations for entity "Winner"
 * 
 * This Bean has a composite Primary Key : WinnerEntityKey
 *
 * @author Telosys Tools Generator
 *
 */
public interface WinnerPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param winner
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(WinnerEntity winner) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param idTicket
	 * @param idDraw
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer idTicket, Integer idDraw) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param winner
	 */
	public void insert(WinnerEntity winner) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param idTicket
	 * @param idDraw
	 * @return the entity loaded (or null if not found)
	 */
	public WinnerEntity load(Integer idTicket, Integer idDraw) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<WinnerEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<WinnerEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<WinnerEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param winner
	 * @return
	 */
	public WinnerEntity save(WinnerEntity winner) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<WinnerEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
